name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: stable
            components: clippy

      - name: Setup cargo-audit
        run: cargo install --force cargo-audit

      - name: Generate Lockfile
        run: cargo generate-lockfile

      - name: Audit
        run: cargo audit

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --release
